const img1 = document.querySelector(".img1")
const rideauBordeau = document.querySelector(".transition")
const img2 = document.querySelector(".img2")
const pageOne = document.querySelector(".pageOne")
const pageTwo = document.querySelector(".pageTwo")
const imgBackground = document.querySelector(".imgBackground")

const borderBox = document.querySelector(".borderBox")
const borderTop = document.querySelector(".border-top")
const borderBottom = document.querySelector(".border-bottom")
const borderLeft = document.querySelector(".border-left")
const borderRight = document.querySelector(".border-right")


const ligneVertical = document.querySelector(".ligneVertical")
const titre = document.querySelector("h1")
const button = document.querySelector("a")

const TL = gsap.timeline()
TL
.to(img1, {y:-500, delay:1})
.to(rideauBordeau, {y:-500, delay:1.5})
.to(rideauBordeau, {y:-1000, delay:1.5}, 3)
.to(img2, {y:-500, delay:1}, 3)
.to(pageOne, {y:"-100vh", duration:1.5, delay:1}, 5)
.to(pageTwo, {bottom:"-0vh", duration:1.5}, 6)
.to(imgBackground, {filter:"blur(20px)", duration:2})
.to(borderBox, {opacity: 1})
.to(borderTop, {bottom:"0px", duration:0.5})
.to(borderLeft, {right:"0px", duration:0.5})
.to(borderRight, {left:"0px", duration:0.5})
.to(borderBottom, {top:"0px", duration:0.5})
.to(borderBox, {backgroundColor: "#00000078"})